<?php
/**
 * Created by PhpStorm.
 * User: gaoruishen
 * Date: 2020/3/27
 * Time: 10:03 AM
 */

namespace GRS\Yii2;

use GRS\Yii2\Auth\AuthClient;
use Yii;
use yii\base\UserException;
use yii\web\Response;

class Controller extends \yii\web\Controller{
    public $layout='layouts/header';
    public $footer="layouts/footer";
    //定义统一用户
    public $user;
    //定义用户权限
    public $hasPermission;

    /**
     * 模板化assign()方法
     */
    public function assign($key, $value) {
        Yii::$app->smarty->assign($key, $value);
    }

    /**
     * 是否跳过登录
     * Controller constructor.
     * @param string $id
     * @param null $module
     */
    public function __construct($id,$module=null) {
        parent::__construct($id,$module);
        if(defined('SKIP_LOGIN')) {
            $this->needLogin = false;
        }
    }

    /**
     * 模板话display方法
     * @param string $view
     * @param array $data
     */
    public function display($view='', $data=array()) {
        if(empty($view)) {
            $controller = $this->id;
            $action = $this->action->id;
            $view = $controller. '/' . $action . '.php';
        }
        if(!empty($data)) {
            foreach($data as $k => $v) {
                $this->assign($k, $v);
            }
        }
        if ($this->needLogin){
            $this->assign('user',$this->user);
        }
        if(!empty($this->layout)) {
            $include_view = $this->formatView($this->layout);
            Yii::$app -> smarty -> display($include_view);
        }
        if(is_array($view)) {
            foreach($view as $row) {
                $include_view = $this->formatView($row);
                Yii::$app -> smarty -> display($include_view);
            }
        } else {
            $include_view = $this->formatView($view);
            Yii::$app -> smarty -> display($include_view);
        }
        if(!empty($this->footer)) {
            $include_view = $this->formatView($this->footer);
            Yii::$app -> smarty -> display($include_view);
        }
    }

    public function formatView($view) {
        $tail = substr($view, -4);
        if($tail!='.php') {
            $view .= '.php';
        }
        return $view;
    }

    public function isLogin() {
        $user = AuthClient::checkAccess();
        if ($user && !empty($user['user'])) {
            $this->hasPermission = !$user['hasPermission'] ? false : true;
            $this->user = $user['user'];
            return true;
        } else return false;
    }

    public function beforeAction($action) {
        if(!parent::beforeAction($action)) {
            return false;
        }

        if ($this->needLogin) {
            if (!$this->isLogin()) {
                if(Yii::$app->request->getIsAjax() ||  Yii::$app->response->format == Response::FORMAT_JSON) {
                    throw new UserException('请先登录后再进行操作','1000');
                }
                AuthClient::redirectToLogin('请先登陆！');
            }
            if (!$this->hasPermission) {
                if(Yii::$app->request->getIsAjax() ||  Yii::$app->response->format == Response::FORMAT_JSON) {
                    throw new UserException('找不到该资源或没有权限','1001');
                }
                AuthClient::redirectToNotFind();
            }
        }
        return true;
    }

    public function afterAction($action, $result)
    {
        $result =  parent::afterAction($action, $result); // TODO: Change the autogenerated stub
        if($result instanceof \yii\base\Response) {
            return $result;
        }
        $request = Yii::$app->getRequest();
        $types = $request->getAcceptableContentTypes();
        if(isset($types['application/json'])) {
            $response = Yii::$app->has('response') ? Yii::$app->getResponse(): new Response();
            $response->data = $result;
            $response->format = Response::FORMAT_JSON;
            return $response;
        }
        return $result;
    }
}